<?php
return [
////////////////////////////////////////////////////////////////////////////
//                                                                        //
//                   WARNING :  DEVIL/SOLID - PACKAGE                     //
//            DO NO ALTER DEFAULT CONFIGURATION UNLESS REQUIRED           //
//                   ALTERING HERE MAY CAUSE MALFUNCTION                  //
//                                                                        //
////////////////////////////////////////////////////////////////////////////
                             //--NOTE:NOTE--//
////////////////////////////////////////////////////////////////////////////
//                                                                        //
//         All Directory Name pattern should match the pattern below      //
//                                                                        //
////////////////////////////////////////////////////////////////////////////
        'modular_app'=>false, // If the app is built on top of module based system design. (Coming soon...)
        'model_schema_json_path' => base_path("data.json"),  // root path/base_path
        'is_api' => true,  // Is this application is developing an api's.
        'api_with_resource_classes'=>true,  // Depends on is_api, This will create an api resources for models if is_api is true.
        'react_with_inertia'=>false, // coming soon...
        'model_path' => "app/Models",
        'controller_path' => "app/Http/Controllers",
        'api_resources_path' => "app/Http/Resources",
        'request_path'=>"app/Http/Requests",
        'view_path' =>"resources/views",  // When is_api is true this will be disabled automatically.
        'migration_path'=>"database/migrations", // Migration Path
        'seeder_path'=>"database/seeders",   // Seeder Path
        'backend_admin_view_path' => "resources/views/backend/admin",  // Storage for View files of Admin/backend.
        'frontend_view_path' => "resources/views/frontend",  // Storage for View files of Frontend.
        // Configuration for Repository design pattern
        'design_pattern'=> "repository", //Design patterns are : none or repository
        'interface_path' => "app/Interfaces",  // Interface Path
        'repo_path' => "app/Repositories",   // Repository Path
        'base_interface_name' => "SolidInterface",  // Base Interface name
        'base_repository_name' => "SolidBaseRepository",  // Base Repository name
        // Other Configuration
        'show_file_already_exists_warning' => false,  //
        'show_folder_already_exists_warning' => false,
        // Override created file : This may delete the contents of previous file generated by SOLID (Not applied Yet)
        'override_previous_file_data' => false,
        "carbon_immutable" => true
      ];
