<?php

return [
////////////////////////////////////////////////////////////////////////////
//                                                                        //
//                   WARNING :  DEVIL/SOLID - PACKAGE                     //
//            DO NO ALTER DEFAULT CONFIGURATION UNLESS REQUIRED           //
//                   ALTERING HERE MAY CAUSE MALFUNCTION                  //
//                                                                        //
////////////////////////////////////////////////////////////////////////////
                                //NOTE:NOTE
////////////////////////////////////////////////////////////////////////////
//                                                                        //
//         All Directory Name pattern should match the pattern below      //
//                                                                        //
////////////////////////////////////////////////////////////////////////////

        'is_repository_design_pattern'=>false,

        'frontend_request_type'=>"BLADE",  // OR "API"   : Note: If API, ReactJS as frontend else Blade.php

        'api_key' => NULL , //DEVIL SOLID API KEY HERE

        'raw_json_data_path' => base_path("data.json"),  // root path/base_path

        'model_path' => "app/Models",

        'controller_path' => "app/Http/Controllers",

        'request_path'=>"app/Http/Requests",

        'view_path' =>"resources/views",

        'migration_path'=>"database/migrations",

        'seeder_path'=>"database/seeders",

        'backend_admin_view_path' => "resources/views/backend/admin",

         'is_api' => false,

        'frontend_view_path' => "resources/views/frontend",

        // Configuration for Repo pattern
        'interface_path' => "app/Interfaces",

        'repo_path' => "app/Repositories",

        'base_interface_name' => "SolidInterface",

        'base_repository_name' => "SolidBaseRepository",


        // Other Configuration
         'show_file_already_exists_warning' => false,

         'show_folder_already_exists_warning' => false,

        // Override created file : This my delete content of previous file generated by SOLID (Not applied Yet)
        'override_previous_file_data' => false,
      ];
